trigger:
  - main
  - master

pool:
  vmImage: ubuntu-latest

variables:
  # Add all your environment variables here
  AZURE_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)
  AZURE_ENV_NAME: $(AZURE_ENV_NAME)
  # ... (add the rest as needed)

steps:
  # Provision Infrastructure using ARM/Bicep template
  - task: AzureResourceManagerTemplateDeployment@3
    displayName: 'Provision Infrastructure'
    inputs:
      deploymentScope: 'Resource Group'
      azureResourceManagerConnection: 'azconnection'
      subscriptionId: '$(AZURE_SUBSCRIPTION_ID)'
      action: 'Create Or Update Resource Group'
      resourceGroupName: '$(AZURE_ENV_NAME)-rg'
      location: '$(AZURE_LOCATION)'
      templateLocation: 'Linked artifact'
      csmFile: 'infra/main.bicep' # or main.json if using ARM
      csmParametersFile: 'infra/main.parameters.json'
      overrideParameters: >
        -environmentName $(AZURE_ENV_NAME)
        # Add other parameters as needed

  # Deploy Web App (example for App Service)
  - task: AzureWebApp@1
    displayName: 'Deploy Web App'
    inputs:
      azureSubscription: 'azconnection'
      appName: '$(AZURE_ENV_NAME)-webapp'
      package: '$(System.DefaultWorkingDirectory)/app/frontend/dist'
